### ISSUE TITLE
Guild Sharding

### ISSUE THREAD

**Issue by Marqin** [rmcafee/discord_ex#27]
Guild Sharding is obligatory for bots with 2500+ guilds:

https://github.com/hammerandchisel/discord-api-docs/issues/17

**Comment by Marqin** [comment]
https://github.com/hammerandchisel/discord-api-docs/blob/master/docs/topics/Gateway.md#get-gateway--get-gatewaybot this gives recomended number of shards bot should connect

**Comment by fcevado** [comment]
Is there any work on automate sharding? Any preference on Poolboy or GenStage?
This package is being maintained?

**Comment by Marqin** [comment]
I didn't had any time for this, and from what I see @rmcafee didn't expanded it much in meantime.

You can try alternative package - https://github.com/Kraigie/nostrum

**Comment by rmcafee** [comment]
Yes my time got very consumed after starting this and many things I wanted to do got shelved including a lot of reworks and additional support for changes made to the discord API. I recommend also checking out nostrum.
