### ISSUE TITLE
Is this project alive ?

### ISSUE THREAD

**Issue by konstantinzolotarev** [rmcafee/discord_ex#40]
Any info about project / author ? 
I see lot of issues and prs unmerged. And nothing from author

**Comment by rmcafee** [comment]
Hey @konstantinzolotarev thanks for the feedback. Do to discord changes and time constraints this project has not received the support it was intended to receive. However, due to new interest and gaining a new co-maintainer we hope to build up traction and progress on a new major version.

**Comment by rmcafee** [comment]
Also, I will update README to reflect that.

**Comment by konstantinzolotarev** [comment]
@rmcafee awesome thank you !
I'd like to help if needed. So feel free to contact
